@{
    Layout = null;
}
<!DOCTYPE HTML>
<html lang="vi">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Nhà hàng Hàn Quốc Suzi</title>
    <style>
        /* Reset mặc định */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            background-color: #333;
            color: #fff;
        }

        header {
            text-align: center;
            padding: 20px;
            background-color: #222;
            border-bottom: 2px solid #ff6f61;
        }

            header h1 {
                font-size: 2.5em;
                color: #ff6f61;
                margin-bottom: 10px;
            }

            header p {
                font-size: 1.2em;
                color: #ccc;
                margin-bottom: 20px;
            }

        nav ul {
            list-style: none;
            padding-top: 10px;
        }

            nav ul li {
                display: inline-block;
                margin: 0 20px;
            }

                nav ul li a {
                    color: #ff6f61;
                    text-decoration: none;
                    font-weight: bold;
                    font-size: 1.1em;
                    padding: 8px 16px;
                    border-radius: 5px;
                    transition: background-color 0.3s ease;
                }

                    nav ul li a:hover {
                        background-color: #ff9f80;
                        color: #fff;
                    }

        #menu {
            padding: 40px;
            background-image: url('https://example.com/chalkboard-background.jpg'); /* Thay URL bằng đường dẫn ảnh nền bảng đen */
            background-size: cover;
            background-position: center;
            text-align: center;
        }

            #menu h2 {
                font-size: 2.5em;
                color: #ff6f61;
                margin-bottom: 20px;
            }

        .menu-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            gap: 20px;
            margin-top: 20px;
        }

        .menu-item {
            background-color: #444;
            padding: 15px;
            border-radius: 10px;
            max-width: 250px;
            text-align: center;
            border: 2px solid #ff6f61;
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);
        }

            .menu-item img {
                max-width: 100%;
                border-radius: 10px;
                margin-bottom: 10px;
            }

            .menu-item h3 {
                margin-top: 10px;
                font-size: 1.8em;
                color: #ff9f80;
            }

            .menu-item p {
                font-size: 1.1em;
                color: #eee;
                margin-top: 10px;
            }

            .menu-item .price {
                font-size: 1.3em;
                color: #ff9f80;
                margin-top: 10px;
            }

        #reservation, #comments, #promotions {
            padding: 40px;
            background-color: #444;
            margin-top: 20px;
            border-radius: 10px;
            max-width: 800px;
            margin: 20px auto;
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);
        }

            #reservation h2, #comments h2, #promotions h2 {
                text-align: center;
                font-size: 2.5em;
                margin-bottom: 20px;
                color: #ff6f61;
            }

        .form-group {
            margin-bottom: 15px;
        }

            .form-group label {
                display: block;
                color: #ff9f80;
                margin-bottom: 5px;
            }

            .form-group input, .form-group textarea {
                width: 100%;
                padding: 10px;
                border-radius: 5px;
                border: none;
                font-size: 1em;
                color: #333;
            }

            .form-group textarea {
                resize: vertical;
            }

        .btn-submit {
            background-color: #ff6f61;
            color: #fff;
            padding: 10px 20px;
            font-size: 1em;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .comment {
            background-color: #555;
            padding: 10px;
            margin: 10px 0;
            border-radius: 5px;
            box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.2);
        }

        .promotions-item {
            background-color: #444;
            padding: 20px;
            margin: 15px 0;
            border-radius: 10px;
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);
        }

            .promotions-item h3 {
                font-size: 1.5em;
                color: #ff9f80;
            }

            .promotions-item p {
                color: #eee;
                font-size: 1.2em;
            }

        footer {
            text-align: center;
            padding: 10px;
            background-color: #222;
            color: #777;
        }

            footer img {
                max-width: 150px;
                margin-top: 10px;
            }
        /* CSS cho logo */
        .logo {
            width: 100px; /* Điều chỉnh kích thước logo */
            height: auto; /* Giữ tỉ lệ logo */
        }
        /* CSS cho header */
        #header .inner {
            text-align: center;
        }

        /* Bao bọc menu */
        .menu-container {
            position: relative;
            padding: 10px;
            border-radius: 10px;
            overflow: hidden; /* Ẩn phần hình ảnh dư thừa */
        }
        #header {
            position: relative;
            padding: 20px;
            background-image: url('https://dulichlive.com/han-quoc/wp-content/uploads/sites/7/2020/02/Tong-hop-20-mon-an-dac-san-Han-Quoc.jpg');
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            text-align: center;
            color: white;
        }

            /* Lớp nền tối mờ */
            #header::before {
                content: "";
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background-color: rgba(0, 0, 0, 0.5); /* Nền tối mờ */
                z-index: 1;
            }

        /* Đảm bảo nội dung nằm trên lớp phủ */
        .inner {
            position: relative;
            z-index: 2; /* Đảm bảo nội dung trong .inner nằm trên lớp phủ */
        }

        .menu-container nav {
            position: relative;
            z-index: 2; /* Đảm bảo menu có thể nhấn được */
        }

        #intro {
            padding: 40px;
            background-color: #333;
            color: #fff;
            text-align: center;
            margin-top: 20px;
            border-radius: 10px;
            max-width: 800px;
            margin: 20px auto;
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);
        }

            #intro h2 {
                font-size: 2.5em;
                color: #ff6f61;
                margin-bottom: 20px;
            }

            #intro p {
                font-size: 1.2em;
                color: #ccc;
                line-height: 1.6;
                margin-bottom: 15px;
            }

.contact-buttons {
    position: fixed;
    bottom: 20px;
    right: 20px;
    display: flex;
    flex-direction: column;
    gap: 10px;
}

.contact-buttons a {
    width: 50px;
    height: 50px;
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: #ff6f61;
    border-radius: 50%;
    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);
    transition: background-color 0.3s ease;
}

.contact-buttons a:hover {
    background-color: #ff9f80;
}

.contact-buttons img {
    width: 24px;
    height: 24px;
}
        .menu-item:hover {
            transform: scale(1.05);
            transition: transform 0.3s ease;
            border-color: #ff9f80;
        }

    </style>
</head>
<body>
    <!-- Header -->
    <header id="header">
        <div class="inner">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQB-Yqka9NHB8-DCb226k0knQItIrTqhZL8YA&s" alt="Logo Suzi" class="logo" />
            <h1>Nhà hàng Hàn Quốc Suzi</h1>
            <p>Trải nghiệm ẩm thực đích thực tại Việt Nam</p>

            <!-- Div bao bọc menu và hình nền -->
            <div class="menu-container">
                <!-- Hình nền bên trong menu-container -->
                <nav>
                    <ul class="menu">
                        <li><a href="#menu" class="menu-item">Món Ăn Nổi Bật</a></li>
                        <li><a href="#intro" class="menu-item">Giới Thiệu</a></li>
                        <li><a href="#reservation" class="menu-item">Đặt Chỗ</a></li>
                        <li><a href="#comments" class="menu-item">Bình Luận</a></li>
                        <li><a href="#promotions" class="menu-item">Khuyến Mãi</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div class="contact-buttons">
        <a href="tel:+84769475076" class="btn-call">
            <img src="https://img.icons8.com/ios-filled/50/ffffff/phone.png" alt="Call Icon">
        </a>
        <a href="https://zalo.me" class="btn-chat">
            <img src="https://img.icons8.com/ios-filled/50/ffffff/chat.png" alt="Chat Icon">
        </a>
    </div>

    <!-- Menu Section -->
    <section id="menu">
        <h2>Những Món Ăn Hàn Quốc Nổi Bật</h2>
        <div class="menu-container">
            <div class="menu-item">
                <img src="https://media.loveitopcdn.com/24813/003539-hancook-2306-blog.png" alt="Kimchi" />
                <h3>Kimchi Hàn Quốc</h3>
                <p>Kimchi truyền thống, một món ăn không thể thiếu trong mỗi bữa ăn Hàn Quốc.</p>
                <p class="price">50,000 VNĐ</p>
            </div>
            <div class="menu-item">
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTPtYBUuNAI6psu8XDrL2RYxI66DC8pUB1lQ&s" alt="Bulgogi" />
                <h3>Bulgogi Nướng</h3>
                <p>Món thịt bò nướng kiểu Hàn, đậm đà hương vị đặc trưng.</p>
                <p class="price">150,000 VNĐ</p>
            </div>
            <div class="menu-item">
                <img src="https://media-cdn2.greatbritishchefs.com/media/plsecugm/img64003.whqc_1426x713q80.jpg" alt="Bibimbap" />
                <h3>Bibimbap</h3>
                <p>Cơm trộn Hàn Quốc với các loại rau, thịt và trứng, ăn kèm với sốt gochujang.</p>
                <p class="price">100,000 VNĐ</p>
            </div>
            <div class="menu-item">
                <img src="https://fullofplants.com/wp-content/uploads/2023/08/Vegan-Jjajang-Tteokbokki-Non-Spicy-Korean-Dish-thumb-1400x1400.jpg" alt="Tteokbokki" />
                <h3>Tteokbokki</h3>
                <p>Bánh gạo Hàn Quốc, cay và ngọt, một món ăn vặt nổi tiếng.</p>
                <p class="price">60,000 VNĐ</p>
            </div>
            <div class="menu-item">
                <img src="https://cdn.tgdd.vn/2021/06/CookProduct/kimbapucgaraucu-1200x676.jpg" alt="Kimbap Gà" />
                <h3>Kimbap Gà</h3>
                <p>Cuộn cơm gà với rau và kimchi, món ăn nhẹ rất phổ biến ở Hàn Quốc.</p>
                <p class="price">70,000 VNĐ</p>
            </div>
            <div class="menu-item">
                <img src="https://i2.wp.com/seonkyounglongest.com/wp-content/uploads/2019/06/samgyeopsal-7.jpg?fit=1300%2C867&ssl=1" alt="Samgyeopsal" />
                <h3>Samgyeopsal</h3>
                <p>Thịt ba chỉ nướng, ăn kèm với rau và gia vị đặc trưng.</p>
                <p class="price">180,000 VNĐ</p>
            </div>
            <div class="menu-item">
                <img src="https://chuyenruouvangnhapkhau.com/upload/default/images/R%C6%B0%E1%BB%A3u%20Soulmate%20soju%20360ml-min.jpg" alt="Soju" />
                <h3>Soju</h3>
                <p>Rượu soju truyền thống Hàn Quốc, uống chung với các món nướng.</p>
                <p class="price">80,000 VNĐ</p>
            </div>
            <div class="menu-item">
                <img src="https://down-vn.img.susercontent.com/file/8cd76378c76f9e9b7c63453dfe7a614d" alt="Trà Sữa" />
                <h3>Trà Sữa Hàn Quốc</h3>
                <p>Trà sữa truyền thống Hàn Quốc với các loại topping thú vị.</p>
                <p class="price">40,000 VNĐ</p>
            </div>
        </div>
    </section>
    <!-- Giới Thiệu Section -->
    <section id="intro">
        <div class="container">
            <h2>Về Nhà Hàng Hàn Quốc Suzi - Tinh Hoa Ẩm Thực Hàn Quốc Tại Việt Nam</h2>
            <p>Nhà hàng Hàn Quốc Suzi là điểm đến lý tưởng cho những ai yêu thích văn hóa và ẩm thực Hàn Quốc tại Việt Nam. Nằm tại trung tâm thành phố, Suzi cam kết mang đến những trải nghiệm ẩm thực chân thực, độc đáo với thực đơn đa dạng từ các món ăn truyền thống như kimchi, bibimbap, và các món nướng Hàn Quốc chuẩn vị.</p>
            <p>Với đội ngũ đầu bếp chuyên nghiệp và giàu kinh nghiệm, nhà hàng Hàn Quốc Suzi không ngừng sáng tạo để mang đến hương vị tinh túy của ẩm thực Hàn Quốc. Chúng tôi luôn sử dụng nguyên liệu tươi ngon, đảm bảo an toàn vệ sinh thực phẩm và chất lượng dịch vụ hàng đầu, để mỗi bữa ăn đều là trải nghiệm đáng nhớ.</p>
            <p>Hãy đến với nhà hàng Hàn Quốc Suzi để thưởng thức không gian ấm cúng, phong cách phục vụ tận tâm và thực đơn đặc trưng Hàn Quốc ngay tại Việt Nam. Chúng tôi mong muốn mang lại sự hài lòng tuyệt đối và trở thành điểm đến yêu thích cho những người yêu ẩm thực Hàn Quốc!</p>
        </div>
    </section>


    <!-- Reservation Section -->
    <section id="reservation">
        <h2>Đặt Chỗ Trực Tuyến</h2>
        <form>
            <div class="form-group">
                <label for="name">Tên của bạn</label>
                <input type="text" id="name" name="name" required />
            </div>
            <div class="form-group">
                <label for="phone">Số điện thoại</label>
                <input type="tel" id="phone" name="phone" required />
            </div>
            <div class="form-group">
                <label for="date">Ngày & Giờ</label>
                <input type="datetime-local" id="date" name="date" required />
            </div>
            <div class="form-group">
                <label for="people">Số lượng người</label>
                <input type="number" id="people" name="people" min="1" required />
            </div>
            <button type="submit" class="btn-submit">Đặt Chỗ</button>
        </form>
    </section>

    <!-- Comments Section -->
    <section id="comments">
        <h2>Ý Kiến Của Khách Hàng</h2>
        <div class="comment">
            <p><strong>Minh Tuấn</strong>: "Món ăn ngon, phục vụ tận tình. Rất hài lòng với dịch vụ của nhà hàng!"</p>
        </div>
        <div class="comment">
            <p><strong>Lan Anh</strong>: "Không gian thoáng đãng, phù hợp cho gia đình và bạn bè quây quần."</p>
        </div>
        <div class="comment">
            <p><strong>Nguyễn Nam</strong>: "Rất thích món Kimchi và Bulgogi ở đây, sẽ quay lại lần sau!"</p>
        </div>
        <h3>Thêm Bình Luận của Bạn:</h3>
        <form>
            <div class="form-group">
                <label for="comment">Bình luận:</label>
                <textarea id="comment" required></textarea>
            </div>
            <button type="submit" class="btn-submit">Gửi Bình Luận</button>
        </form>

    </section>

    <!-- Promotions Section -->
    <section id="promotions">
        <h2>Khuyến Mãi Đặc Biệt</h2>
        <div class="promotions-item">
            <h3>Giảm giá 20% cho lần ăn đầu tiên</h3>
            <p>Nhận ngay 20% giảm giá khi bạn đặt bàn lần đầu tiên tại nhà hàng Suzi.</p>
        </div>
        <div class="promotions-item">
            <h3>Combo gia đình</h3>
            <p>Chọn combo món ăn đặc biệt dành cho gia đình với giá ưu đãi đặc biệt.</p>
        </div>
    </section>

    <!-- Footer -->
    <footer>
        <div class="footer-content">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQB-Yqka9NHB8-DCb226k0knQItIrTqhZL8YA&s" alt="Logo Suzi" />

            <div class="contact-info">
                <p>Điện thoại: (024) 123 456 789</p>
                <p>Email: info@suzirestaurant.com</p>
                <p>Địa chỉ 1: 123 Đường ABC, Quận XYZ, Hà Nội</p>
                <p>Địa chỉ 2: 123 Đường ABC, Quận XYZ, Hà Nội</p>
            </div>
            <div class="social-media">
                <a href="https://facebook.com/suzirestaurant" target="_blank">Facebook</a>
                <a href="https://instagram.com/suzirestaurant" target="_blank">Instagram</a>
                <a href="https://zalo.me/suzirestaurant" target="_blank">Zalo</a>
            </div>
            <p>© 2024 Nhà hàng Hàn Quốc Suzi. Ngô Thành Hữu.</p>
        </div>
    </footer>


</body>
</html>
